# Generated by Django 3.2.6 on 2021-09-13 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
